config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)
  get 'trades/index'

  resources :trades, :offers do
    resources :items
  end

  root 'trades#index'

end

app/models/active_admin_adapter.rb
class ActiveAdminAdapter < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user.admin == true
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/item.rb
class Item < ActiveRecord::Base
	mount_uploader :image, ImageUploader, :on => :file_name
	validates_presence_of :image
	belongs_to :trade
end

app/models/offer.rb
class Offer < ActiveRecord::Base
	validates :description, presence: true, length: {in: 25..1000}
	has_many :items

	accepts_nested_attributes_for :items
end

app/models/trade.rb
class Trade < ActiveRecord::Base
	validates :title, presence: true, length: { minimum: 5 }
	validates :description, presence: true, length: {in: 25..1000}
	validates :user_id, presence: true
	has_many :items, dependent: :destroy

	accepts_nested_attributes_for :items
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :trades
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def access_denied(exception)
  	redirect_to root_path, alert:exception.message
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
		def show
			@trade = Trade.find(params[:trade_id])
			@item = @trade.items.find(params[:id])
		end

	def new
	end
	
  def update
     @trade = Trade.find(params[:trade_id])
     @item = @trade.items.find(params[:id])
  end
  
	def edit
	  @trade = Trade.find(params[:trade_id])
	  @item = @trade.items.find(params[:id])
	end

	def create
		@trade = Trade.find(params[:trade_id])
		@item = @trade.items.create(item_params)
		if @item.save
			redirect_to trade_path(@trade)
		else
			render 'edit'
		end
	end

# Editing nested items currently busted, TODO fix this
#	def update 
#		@trade = Trade.find(params[:id])
#		@item = @trade.items.create(item_params)
#		if @item.update(item_params)
#			redirect_to @trade
#		else
#			render 'edit'
#		end
#	end

  def destroy
    @trade = Trade.find(params[:trade_id])
    @item = @trade.items.find(params[:id])
    @item.destroy
    redirect_to trade_path(@trade)
  end


	private
		def item_params
			params.require(:item).permit(:title, :description, :image)
		end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
	def new
	end

	def create
		@offer = Offer.new(offer_params)
		@offer.save

		redirect_to @offer
	end

	private
		def offer_params
			params.require(:offer).permit(:title, :description)
		end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
	def index
		@trades = Trade.all
	end

	def show
		@trade = Trade.find(params[:id])
	end

	def new
		@trade = Trade.new
	end

	def edit
	  @trade = Trade.find(params[:id])
	end

	def create
		@trade = current_user.trades.build(trade_params)
		if @trade.save
			redirect_to @trade
		else
			render 'new'
		end
	end

	def update 
		@trade = Trade.find(params[:id])

		if @trade.update(trade_params)
			redirect_to @trade
		else
			render 'edit'
		end
	end

	private
		def trade_params
			params.require(:trade).permit(:title, :description, :tags, :user_id)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/items/_add_item.html.erb
<h2>Add an item:</h2>
<%= form_for([@trade, @trade.items.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <div class="uploader">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/items/_item.html.erb
<h3 class="intro-header intro">Items in this trade</h3>
<div id="main_container" class='container'>
  <div class="row"> 
    <% @trade.items.each do |item| %>
      <div class="col-lg-4 col-sm-6 col-xs-12 grid-item">
        <%= if item.image != nil 
                link_to item.image.url do 
                  image_tag item.image.medium.url 
                end 
            end %>
        <h3><%= item.title %></h3>
        <p><%= item.description %></p>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <%= render 'layouts/navigation_links' %>
  <%= render 'devise/login_items' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Requine" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Requine" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
      <%= image_tag("searles_valley_small.jpg", class: "background-img") %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/trades/_trade_add_form.html.erb
<%= form_for @trade do |f| %>

  <% if @trade.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@trade.errors.count, "error") %> prohibited
        this trade from being published:
      </h2>
      <ul>
        <% @trade.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form_for :trade, url: trades_path do |f| %>
  	<p>
  		<%= f.label :title %><br>
  		<%= f.text_field :title %>
  	</p>
  	<p>
  		<%= f.label :description %><br>
  		<%= f.text_area :description %>
  	</p>
  	<p>
  		<%= f.label :tags %><br>
  		<%= f.text_field :tags %>
  	</p>
  	<p>
  		<%= f.submit %>
  	</p>
  <% end %>
<% end %>

app/views/trades/edit.html.erb
<h1>Editing trade /"<% :title %>/"</h1>
 
<%= render 'trade_add_form' %>
 
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<div class="intro">
  <h3 class="intro-header">Hi, my name is Ralph Alexander.</h3> 
  <p class="blurb">I am a general tinkerer with a lot of ongoing toolmaking, machinery restoration and automotive projects. I have become tired of not being able to relate the inventory of parts I either have or need to you, my fellow hoarders. So I have decided to make my own listings in order to do just that. <br>
  You can submit an offer on any of the parts or tools I have, or just get in contact about anything here. Just click on any of the Trades in the list below to get started. Please provide photos of the items you are offering in trade so we both know what we are dealing with.</p>
</div>

<h3 class="intro-header">Things I am Looking to Trade</h3>
<div id="main_container" class='container'>
  <div class="row">  
    <% @trades.each do |trade| %>
      <div class="col-lg-6 col-sm-6 col-xs-12 grid-item">
          <%= link_to(trade_path(trade)) do %>
            <%= if trade.items[0] && trade.items[0].image != nil
                image_tag trade.items[0].image.medium.url
              end %>
            <h3><%= trade.title %></h3>
          <% end %>
          <p><%= trade.description %></p>
        </div>
    <% end %>
  </div>
</div>

<%= if current_user.try(:admin?)
    link_to 'New Trade', new_trade_path
  end 
  %>

app/views/trades/new.html.erb
<h1>New Trade<h1>

<%= render 'trade_add_form' %>

<%= link_to 'Back', trades_path %>

</div>

app/views/trades/show.html.erb
<div class="intro">
	<h3 class="intro-header"><%= @trade.title %></h3>
 
	<p class="blurb">
	  <%= @trade.description %>
	</p>
	<p class="tags">
  		<%= @trade.tags %>
	</p>
</div>



<%= render 'items/item' %>

<%= if current_user.try(:admin?)
	 render 'items/add_item' 
	end %>

<%= if  current_user.try(:admin?)
	 link_to 'Edit', edit_trade_path(@trade) 
	end %> |
<%= link_to 'Back', trades_path %>